// <auto-generated />
namespace De.Brickmakers.Tutorials.EF.DatabaseLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedTeachers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedTeachers));
        
        string IMigrationMetadata.Id
        {
            get { return "201511060912315_Added Teachers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
